### ISSUE TITLE
AttributeError: 'LMContext' object has no attribute 's'

### ISSUE THREAD

**Issue by Minami-su** [genlm/llamppl#11]
https://colab.research.google.com/drive/1uJEC-U8dcwsTWccCDGVexpgXexzZ642n?usp=sharing#scrollTo=gsi7R6D0NcGn&uniqifier=1
![image](https://github.com/probcomp/hfppl/assets/76865636/71d2b70e-b8fb-4648-866f-9d03d73f51d3)
   
  10         self.lm         = LMContext(LLM, prompt)
     11         self.q          = LMContext(LLM, prompt)
---> 12         self.prompt_len = len(str(self.lm.s))
     13         self.max_tokens = max_tokens
     14 

AttributeError: 'LMContext' object has no attribute 's'

**Comment by alex-lew** [comment]
Thanks! The Colab has now been updated -- it had become out of sync with the repo.
