### ISSUE TITLE
Removing `transformers==4.30` requirement

### ISSUE THREAD

**Issue by jagilley** [genlm/llamppl#4]
I haven't tested comprehensively as I don't know what error was coming up with transformers > 4.30, but I'm pretty sure that if line  238 of `llms.py` is changed from

```python
logits = self.model(torch.tensor([[self.tokenizer.bos_token_id]]).to(self.model.device)).loss['logits'][0][0]
```
to
```python
logits = self.model(torch.tensor([[self.tokenizer.bos_token_id]]).to(self.model.device)).logits[0][0]
```
that will allow the latest HF Transformers package to be installed. I've tested it, and it's working for me on `transformers==4.35`. Interestingly, this allows for use with Mistral's 7B model!

Submitting an issue instead of a PR for now as I haven't tested comprehensively when line 238 does and doesn't work with respect to HF transformers versions.

**Comment by alex-lew** [comment]
Thanks!! Fixed.
